# Generated by:
#
#     mix ichor.gen priv/grammar/xeger.aether --module Xeger.Grammar --actions Xeger.Parser.Actions --out lib/xeger/grammar.ex
#
# Do not edit by hand -- rerun the command above instead.
defmodule Xeger.Grammar do
  @moduledoc false
  (
    @dialyzer [:no_opaque, :no_match]
    alias Grammar.Native.Runtime.{Parser, Tokenizer}
    alias Grammar.VM.Token

    def lex_token__PIPE(input) do
      case input do
        <<"|", rest::binary>> -> {:ok, "|", rest}
        _ -> :fail
      end
    end

    def lex_token__DIGIT(input) do
      case input do
        <<c::utf8, rest::binary>> ->
          if Tokenizer.in_ranges?(c, [{48, 57}]) do
            {:ok, <<c::utf8>>, rest}
          else
            :fail
          end

        _ ->
          :fail
      end
    end

    def lex_token__ALPHA(input) do
      case input do
        <<c::utf8, rest::binary>> ->
          if Tokenizer.in_ranges?(c, [{97, 122}, {65, 90}]) do
            {:ok, <<c::utf8>>, rest}
          else
            :fail
          end

        _ ->
          :fail
      end
    end

    def lex_expr__0(input) do
      case input do
        <<c::utf8, rest::binary>> ->
          if Tokenizer.in_ranges?(c, [{48, 57}]) do
            {:ok, <<c::utf8>>, rest}
          else
            :fail
          end

        _ ->
          :fail
      end
    end

    def lex_expr__1(input) do
      case input do
        <<c::utf8, rest::binary>> ->
          if Tokenizer.in_ranges?(c, [{97, 122}, {65, 90}]) do
            {:ok, <<c::utf8>>, rest}
          else
            :fail
          end

        _ ->
          :fail
      end
    end

    def lex_token__ALNUM(input) do
      Tokenizer.first_char_match([&lex_expr__0/1, &lex_expr__1/1], input)
    end

    def lex_token__SPACE(input) do
      case input do
        <<c::utf8, rest::binary>> ->
          if Tokenizer.in_ranges?(c, [{32, 32}, {9, 9}, {13, 13}, {10, 10}]) do
            {:ok, <<c::utf8>>, rest}
          else
            :fail
          end

        _ ->
          :fail
      end
    end

    def lex_token__HEX(input) do
      case input do
        <<c::utf8, rest::binary>> ->
          if Tokenizer.in_ranges?(c, [{97, 102}, {65, 70}, {48, 57}]) do
            {:ok, <<c::utf8>>, rest}
          else
            :fail
          end

        _ ->
          :fail
      end
    end

    def lex_token__LPAREN(input) do
      case input do
        <<"(", rest::binary>> -> {:ok, "(", rest}
        _ -> :fail
      end
    end

    def lex_token__RPAREN(input) do
      case input do
        <<")", rest::binary>> -> {:ok, ")", rest}
        _ -> :fail
      end
    end

    def lex_token__LBRACKET(input) do
      case input do
        <<"[", rest::binary>> -> {:ok, "[", rest}
        _ -> :fail
      end
    end

    def lex_token__RBRACKET(input) do
      case input do
        <<"]", rest::binary>> -> {:ok, "]", rest}
        _ -> :fail
      end
    end

    def lex_token__LBRACE(input) do
      case input do
        <<"{", rest::binary>> -> {:ok, "{", rest}
        _ -> :fail
      end
    end

    def lex_token__RBRACE(input) do
      case input do
        <<"}", rest::binary>> -> {:ok, "}", rest}
        _ -> :fail
      end
    end

    def lex_token__CARET(input) do
      case input do
        <<"^", rest::binary>> -> {:ok, "^", rest}
        _ -> :fail
      end
    end

    def lex_token__DASH(input) do
      case input do
        <<"-", rest::binary>> -> {:ok, "-", rest}
        _ -> :fail
      end
    end

    def lex_token__STAR(input) do
      case input do
        <<"*", rest::binary>> -> {:ok, "*", rest}
        _ -> :fail
      end
    end

    def lex_token__PLUS(input) do
      case input do
        <<"+", rest::binary>> -> {:ok, "+", rest}
        _ -> :fail
      end
    end

    def lex_token__QUESTION(input) do
      case input do
        <<"?", rest::binary>> -> {:ok, "?", rest}
        _ -> :fail
      end
    end

    def lex_token__COMMA(input) do
      case input do
        <<",", rest::binary>> -> {:ok, ",", rest}
        _ -> :fail
      end
    end

    def lex_token__DOT(input) do
      case input do
        <<".", rest::binary>> -> {:ok, ".", rest}
        _ -> :fail
      end
    end

    def lex_expr__2(input) do
      case input do
        <<"\\d", rest::binary>> -> {:ok, "\\d", rest}
        _ -> :fail
      end
    end

    def lex_expr__3(input) do
      case input do
        <<"\\w", rest::binary>> -> {:ok, "\\w", rest}
        _ -> :fail
      end
    end

    def lex_expr__4(input) do
      case input do
        <<"\\s", rest::binary>> -> {:ok, "\\s", rest}
        _ -> :fail
      end
    end

    def lex_token__SHORTHAND_CLASS(input) do
      Tokenizer.first_char_match([&lex_expr__2/1, &lex_expr__3/1, &lex_expr__4/1], input)
    end

    def lex_expr__5(input) do
      case input do
        <<"\\", rest::binary>> -> {:ok, "\\", rest}
        _ -> :fail
      end
    end

    def lex_expr__6(input) do
      case input do
        <<c::utf8, rest::binary>> -> {:ok, <<c::utf8>>, rest}
        _ -> :fail
      end
    end

    def lex_token__ESCAPED_CHAR(input0) do
      with {:ok, t0, rest0} <- lex_expr__5(input0), {:ok, t1, rest1} <- lex_expr__6(rest0) do
        {:ok, t0 <> t1, rest1}
      else
        :fail -> :fail
      end
    end

    def lex_expr__9(input) do
      case input do
        <<"(", rest::binary>> -> {:ok, "(", rest}
        _ -> :fail
      end
    end

    def lex_expr__10(input) do
      case input do
        <<")", rest::binary>> -> {:ok, ")", rest}
        _ -> :fail
      end
    end

    def lex_expr__11(input) do
      case input do
        <<"[", rest::binary>> -> {:ok, "[", rest}
        _ -> :fail
      end
    end

    def lex_expr__12(input) do
      case input do
        <<"]", rest::binary>> -> {:ok, "]", rest}
        _ -> :fail
      end
    end

    def lex_expr__13(input) do
      case input do
        <<"{", rest::binary>> -> {:ok, "{", rest}
        _ -> :fail
      end
    end

    def lex_expr__14(input) do
      case input do
        <<"}", rest::binary>> -> {:ok, "}", rest}
        _ -> :fail
      end
    end

    def lex_expr__15(input) do
      case input do
        <<"^", rest::binary>> -> {:ok, "^", rest}
        _ -> :fail
      end
    end

    def lex_expr__16(input) do
      case input do
        <<"-", rest::binary>> -> {:ok, "-", rest}
        _ -> :fail
      end
    end

    def lex_expr__17(input) do
      case input do
        <<"*", rest::binary>> -> {:ok, "*", rest}
        _ -> :fail
      end
    end

    def lex_expr__18(input) do
      case input do
        <<"+", rest::binary>> -> {:ok, "+", rest}
        _ -> :fail
      end
    end

    def lex_expr__19(input) do
      case input do
        <<"?", rest::binary>> -> {:ok, "?", rest}
        _ -> :fail
      end
    end

    def lex_expr__20(input) do
      case input do
        <<"|", rest::binary>> -> {:ok, "|", rest}
        _ -> :fail
      end
    end

    def lex_expr__21(input) do
      case input do
        <<".", rest::binary>> -> {:ok, ".", rest}
        _ -> :fail
      end
    end

    def lex_expr__22(input) do
      case input do
        <<",", rest::binary>> -> {:ok, ",", rest}
        _ -> :fail
      end
    end

    def lex_expr__8(input) do
      Tokenizer.first_char_match(
        [
          &lex_expr__9/1,
          &lex_expr__10/1,
          &lex_expr__11/1,
          &lex_expr__12/1,
          &lex_expr__13/1,
          &lex_expr__14/1,
          &lex_expr__15/1,
          &lex_expr__16/1,
          &lex_expr__17/1,
          &lex_expr__18/1,
          &lex_expr__19/1,
          &lex_expr__20/1,
          &lex_expr__21/1,
          &lex_expr__22/1
        ],
        input
      )
    end

    def lex_expr__7(input) do
      Tokenizer.not_pred_char(&lex_expr__8/1, input)
    end

    def lex_expr__23(input) do
      case input do
        <<c::utf8, rest::binary>> -> {:ok, <<c::utf8>>, rest}
        _ -> :fail
      end
    end

    def lex_token__LITERAL_CHAR(input0) do
      with {:ok, t0, rest0} <- lex_expr__7(input0), {:ok, t1, rest1} <- lex_expr__23(rest0) do
        {:ok, t0 <> t1, rest1}
      else
        :fail -> :fail
      end
    end

    def lex_candidates(input, _context) do
      [
        LPAREN: fn ->
          case lex_token__LPAREN(input) do
            {:ok, text, rest} -> {:ok, text, rest, nil}
            :fail -> :fail
          end
        end,
        RPAREN: fn ->
          case lex_token__RPAREN(input) do
            {:ok, text, rest} -> {:ok, text, rest, nil}
            :fail -> :fail
          end
        end,
        LBRACKET: fn ->
          case lex_token__LBRACKET(input) do
            {:ok, text, rest} -> {:ok, text, rest, nil}
            :fail -> :fail
          end
        end,
        RBRACKET: fn ->
          case lex_token__RBRACKET(input) do
            {:ok, text, rest} -> {:ok, text, rest, nil}
            :fail -> :fail
          end
        end,
        LBRACE: fn ->
          case lex_token__LBRACE(input) do
            {:ok, text, rest} -> {:ok, text, rest, nil}
            :fail -> :fail
          end
        end,
        RBRACE: fn ->
          case lex_token__RBRACE(input) do
            {:ok, text, rest} -> {:ok, text, rest, nil}
            :fail -> :fail
          end
        end,
        CARET: fn ->
          case lex_token__CARET(input) do
            {:ok, text, rest} -> {:ok, text, rest, nil}
            :fail -> :fail
          end
        end,
        DASH: fn ->
          case lex_token__DASH(input) do
            {:ok, text, rest} -> {:ok, text, rest, nil}
            :fail -> :fail
          end
        end,
        STAR: fn ->
          case lex_token__STAR(input) do
            {:ok, text, rest} -> {:ok, text, rest, nil}
            :fail -> :fail
          end
        end,
        PLUS: fn ->
          case lex_token__PLUS(input) do
            {:ok, text, rest} -> {:ok, text, rest, nil}
            :fail -> :fail
          end
        end,
        QUESTION: fn ->
          case lex_token__QUESTION(input) do
            {:ok, text, rest} -> {:ok, text, rest, nil}
            :fail -> :fail
          end
        end,
        PIPE: fn ->
          case lex_token__PIPE(input) do
            {:ok, text, rest} -> {:ok, text, rest, nil}
            :fail -> :fail
          end
        end,
        COMMA: fn ->
          case lex_token__COMMA(input) do
            {:ok, text, rest} -> {:ok, text, rest, nil}
            :fail -> :fail
          end
        end,
        DOT: fn ->
          case lex_token__DOT(input) do
            {:ok, text, rest} -> {:ok, text, rest, nil}
            :fail -> :fail
          end
        end,
        SHORTHAND_CLASS: fn ->
          case lex_token__SHORTHAND_CLASS(input) do
            {:ok, text, rest} -> {:ok, text, rest, nil}
            :fail -> :fail
          end
        end,
        ESCAPED_CHAR: fn ->
          case lex_token__ESCAPED_CHAR(input) do
            {:ok, text, rest} -> {:ok, text, rest, nil}
            :fail -> :fail
          end
        end,
        DIGIT: fn ->
          case lex_token__DIGIT(input) do
            {:ok, text, rest} -> {:ok, text, rest, nil}
            :fail -> :fail
          end
        end,
        LITERAL_CHAR: fn ->
          case lex_token__LITERAL_CHAR(input) do
            {:ok, text, rest} -> {:ok, text, rest, nil}
            :fail -> :fail
          end
        end
      ]
    end

    def parse_expr__0(stream, pos, ref_stack, context) do
      case parse_rule__group(stream, pos, ref_stack, context) do
        {:ok, new_pos, new_ref_stack, sub_captures} ->
          {:ok, new_pos, new_ref_stack, group: {:rule, :group, sub_captures}}

        _fail ->
          :fail
      end
    end

    def parse_expr__1(stream, pos, ref_stack, context) do
      case parse_rule__char_class(stream, pos, ref_stack, context) do
        {:ok, new_pos, new_ref_stack, sub_captures} ->
          {:ok, new_pos, new_ref_stack, char_class: {:rule, :char_class, sub_captures}}

        _fail ->
          :fail
      end
    end

    def parse_expr__2(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :DOT) do
        {:ok, new_pos, text, nil} -> {:ok, new_pos, ref_stack, DOT: {:token, :DOT, text}}
        {:ok, new_pos, _text, capture} -> {:ok, new_pos, ref_stack, DOT: capture}
        :fail -> :fail
      end
    end

    def parse_expr__3(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :SHORTHAND_CLASS) do
        {:ok, new_pos, text, nil} ->
          {:ok, new_pos, ref_stack, SHORTHAND_CLASS: {:token, :SHORTHAND_CLASS, text}}

        {:ok, new_pos, _text, capture} ->
          {:ok, new_pos, ref_stack, SHORTHAND_CLASS: capture}

        :fail ->
          :fail
      end
    end

    def parse_expr__4(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :ESCAPED_CHAR) do
        {:ok, new_pos, text, nil} ->
          {:ok, new_pos, ref_stack, ESCAPED_CHAR: {:token, :ESCAPED_CHAR, text}}

        {:ok, new_pos, _text, capture} ->
          {:ok, new_pos, ref_stack, ESCAPED_CHAR: capture}

        :fail ->
          :fail
      end
    end

    def parse_expr__5(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :CARET) do
        {:ok, new_pos, text, nil} -> {:ok, new_pos, ref_stack, CARET: {:token, :CARET, text}}
        {:ok, new_pos, _text, capture} -> {:ok, new_pos, ref_stack, CARET: capture}
        :fail -> :fail
      end
    end

    def parse_expr__6(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :DASH) do
        {:ok, new_pos, text, nil} -> {:ok, new_pos, ref_stack, DASH: {:token, :DASH, text}}
        {:ok, new_pos, _text, capture} -> {:ok, new_pos, ref_stack, DASH: capture}
        :fail -> :fail
      end
    end

    def parse_expr__7(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :COMMA) do
        {:ok, new_pos, text, nil} -> {:ok, new_pos, ref_stack, COMMA: {:token, :COMMA, text}}
        {:ok, new_pos, _text, capture} -> {:ok, new_pos, ref_stack, COMMA: capture}
        :fail -> :fail
      end
    end

    def parse_expr__8(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :DIGIT) do
        {:ok, new_pos, text, nil} -> {:ok, new_pos, ref_stack, DIGIT: {:token, :DIGIT, text}}
        {:ok, new_pos, _text, capture} -> {:ok, new_pos, ref_stack, DIGIT: capture}
        :fail -> :fail
      end
    end

    def parse_expr__9(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :LITERAL_CHAR) do
        {:ok, new_pos, text, nil} ->
          {:ok, new_pos, ref_stack, LITERAL_CHAR: {:token, :LITERAL_CHAR, text}}

        {:ok, new_pos, _text, capture} ->
          {:ok, new_pos, ref_stack, LITERAL_CHAR: capture}

        :fail ->
          :fail
      end
    end

    def parse_rule__atom(stream, pos, ref_stack, context) do
      Parser.try_alts(
        [
          &parse_expr__0/4,
          &parse_expr__1/4,
          &parse_expr__2/4,
          &parse_expr__3/4,
          &parse_expr__4/4,
          &parse_expr__5/4,
          &parse_expr__6/4,
          &parse_expr__7/4,
          &parse_expr__8/4,
          &parse_expr__9/4
        ],
        stream,
        pos,
        ref_stack,
        context
      )
    end

    def parse_expr__10(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :LBRACE) do
        {:ok, new_pos, text, nil} -> {:ok, new_pos, ref_stack, LBRACE: {:token, :LBRACE, text}}
        {:ok, new_pos, _text, capture} -> {:ok, new_pos, ref_stack, LBRACE: capture}
        :fail -> :fail
      end
    end

    def parse_expr__13(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :DIGIT) do
        {:ok, new_pos, text, nil} -> {:ok, new_pos, ref_stack, DIGIT: {:token, :DIGIT, text}}
        {:ok, new_pos, _text, capture} -> {:ok, new_pos, ref_stack, DIGIT: capture}
        :fail -> :fail
      end
    end

    def parse_expr__12(stream, pos, ref_stack, context) do
      Parser.plus(&parse_expr__13/4, stream, pos, ref_stack, context)
    end

    def parse_expr__11(stream, pos, ref_stack, context) do
      case (&parse_expr__12/4).(stream, pos, ref_stack, context) do
        {:ok, new_pos, new_ref_stack, inner_caps} ->
          text = Parser.concat_text(stream, pos, new_pos)
          {:ok, new_pos, new_ref_stack, Parser.merge_captures(inner_caps, min: {:text, text})}

        _fail ->
          :fail
      end
    end

    def parse_expr__16(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :COMMA) do
        {:ok, new_pos, text, nil} -> {:ok, new_pos, ref_stack, COMMA: {:token, :COMMA, text}}
        {:ok, new_pos, _text, capture} -> {:ok, new_pos, ref_stack, COMMA: capture}
        :fail -> :fail
      end
    end

    def parse_expr__19(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :DIGIT) do
        {:ok, new_pos, text, nil} -> {:ok, new_pos, ref_stack, DIGIT: {:token, :DIGIT, text}}
        {:ok, new_pos, _text, capture} -> {:ok, new_pos, ref_stack, DIGIT: capture}
        :fail -> :fail
      end
    end

    def parse_expr__18(stream, pos, ref_stack, context) do
      Parser.star(&parse_expr__19/4, stream, pos, ref_stack, context)
    end

    def parse_expr__17(stream, pos, ref_stack, context) do
      case (&parse_expr__18/4).(stream, pos, ref_stack, context) do
        {:ok, new_pos, new_ref_stack, inner_caps} ->
          text = Parser.concat_text(stream, pos, new_pos)
          {:ok, new_pos, new_ref_stack, Parser.merge_captures(inner_caps, max: {:text, text})}

        _fail ->
          :fail
      end
    end

    def parse_expr__15(stream, pos, ref_stack, context) do
      with {:ok, pos1, ref1, cap0} <- parse_expr__16(stream, pos, ref_stack, context),
           {:ok, pos2, ref2, cap1} <- parse_expr__17(stream, pos1, ref1, context) do
        {:ok, pos2, ref2, Parser.merge_captures(cap0, cap1)}
      else
        _fail -> :fail
      end
    end

    def parse_expr__14(stream, pos, ref_stack, context) do
      Parser.opt(&parse_expr__15/4, stream, pos, ref_stack, context)
    end

    def parse_expr__20(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :RBRACE) do
        {:ok, new_pos, text, nil} -> {:ok, new_pos, ref_stack, RBRACE: {:token, :RBRACE, text}}
        {:ok, new_pos, _text, capture} -> {:ok, new_pos, ref_stack, RBRACE: capture}
        :fail -> :fail
      end
    end

    def parse_rule__bound(stream, pos, ref_stack, context) do
      with {:ok, pos1, ref1, cap0} <- parse_expr__10(stream, pos, ref_stack, context),
           {:ok, pos2, ref2, cap1} <- parse_expr__11(stream, pos1, ref1, context),
           {:ok, pos3, ref3, cap2} <- parse_expr__14(stream, pos2, ref2, context),
           {:ok, pos4, ref4, cap3} <- parse_expr__20(stream, pos3, ref3, context) do
        {:ok, pos4, ref4,
         Parser.merge_captures(
           cap0,
           Parser.merge_captures(cap1, Parser.merge_captures(cap2, cap3))
         )}
      else
        _fail -> :fail
      end
    end

    def parse_expr__22(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :LPAREN) do
        {:ok, new_pos, text, nil} -> {:ok, new_pos, ref_stack, LPAREN: {:token, :LPAREN, text}}
        {:ok, new_pos, _text, capture} -> {:ok, new_pos, ref_stack, LPAREN: capture}
        :fail -> :fail
      end
    end

    def parse_expr__23(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :RPAREN) do
        {:ok, new_pos, text, nil} -> {:ok, new_pos, ref_stack, RPAREN: {:token, :RPAREN, text}}
        {:ok, new_pos, _text, capture} -> {:ok, new_pos, ref_stack, RPAREN: capture}
        :fail -> :fail
      end
    end

    def parse_expr__21(stream, pos, ref_stack, context) do
      with {:ok, pos1, ref1, cap0} <- parse_expr__22(stream, pos, ref_stack, context),
           {:ok, pos2, ref2, cap1} <- parse_expr__23(stream, pos1, ref1, context) do
        {:ok, pos2, ref2, Parser.merge_captures(cap0, cap1)}
      else
        _fail -> :fail
      end
    end

    def parse_expr__25(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :LPAREN) do
        {:ok, new_pos, text, nil} -> {:ok, new_pos, ref_stack, LPAREN: {:token, :LPAREN, text}}
        {:ok, new_pos, _text, capture} -> {:ok, new_pos, ref_stack, LPAREN: capture}
        :fail -> :fail
      end
    end

    def parse_expr__26(stream, pos, ref_stack, context) do
      case parse_rule__expr(stream, pos, ref_stack, context) do
        {:ok, new_pos, new_ref_stack, sub_captures} ->
          {:ok, new_pos, new_ref_stack, body: {:rule, :expr, sub_captures}}

        _fail ->
          :fail
      end
    end

    def parse_expr__27(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :RPAREN) do
        {:ok, new_pos, text, nil} -> {:ok, new_pos, ref_stack, RPAREN: {:token, :RPAREN, text}}
        {:ok, new_pos, _text, capture} -> {:ok, new_pos, ref_stack, RPAREN: capture}
        :fail -> :fail
      end
    end

    def parse_expr__24(stream, pos, ref_stack, context) do
      with {:ok, pos1, ref1, cap0} <- parse_expr__25(stream, pos, ref_stack, context),
           {:ok, pos2, ref2, cap1} <- parse_expr__26(stream, pos1, ref1, context),
           {:ok, pos3, ref3, cap2} <- parse_expr__27(stream, pos2, ref2, context) do
        {:ok, pos3, ref3, Parser.merge_captures(cap0, Parser.merge_captures(cap1, cap2))}
      else
        _fail -> :fail
      end
    end

    def parse_rule__group(stream, pos, ref_stack, context) do
      Parser.try_alts([&parse_expr__21/4, &parse_expr__24/4], stream, pos, ref_stack, context)
    end

    def parse_expr__28(stream, pos, ref_stack, context) do
      case parse_rule__piece(stream, pos, ref_stack, context) do
        {:ok, new_pos, new_ref_stack, sub_captures} ->
          {:ok, new_pos, new_ref_stack, piece: {:rule, :piece, sub_captures}}

        _fail ->
          :fail
      end
    end

    def parse_rule__concat(stream, pos, ref_stack, context) do
      Parser.plus(&parse_expr__28/4, stream, pos, ref_stack, context)
    end

    def parse_expr__29(stream, pos, ref_stack, context) do
      case parse_rule__concat(stream, pos, ref_stack, context) do
        {:ok, new_pos, new_ref_stack, sub_captures} ->
          {:ok, new_pos, new_ref_stack, concat: {:rule, :concat, sub_captures}}

        _fail ->
          :fail
      end
    end

    def parse_expr__32(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :PIPE) do
        {:ok, new_pos, text, nil} -> {:ok, new_pos, ref_stack, PIPE: {:token, :PIPE, text}}
        {:ok, new_pos, _text, capture} -> {:ok, new_pos, ref_stack, PIPE: capture}
        :fail -> :fail
      end
    end

    def parse_expr__33(stream, pos, ref_stack, context) do
      case parse_rule__concat(stream, pos, ref_stack, context) do
        {:ok, new_pos, new_ref_stack, sub_captures} ->
          {:ok, new_pos, new_ref_stack, concat: {:rule, :concat, sub_captures}}

        _fail ->
          :fail
      end
    end

    def parse_expr__31(stream, pos, ref_stack, context) do
      with {:ok, pos1, ref1, cap0} <- parse_expr__32(stream, pos, ref_stack, context),
           {:ok, pos2, ref2, cap1} <- parse_expr__33(stream, pos1, ref1, context) do
        {:ok, pos2, ref2, Parser.merge_captures(cap0, cap1)}
      else
        _fail -> :fail
      end
    end

    def parse_expr__30(stream, pos, ref_stack, context) do
      Parser.star(&parse_expr__31/4, stream, pos, ref_stack, context)
    end

    def parse_rule__expr(stream, pos, ref_stack, context) do
      with {:ok, pos1, ref1, cap0} <- parse_expr__29(stream, pos, ref_stack, context),
           {:ok, pos2, ref2, cap1} <- parse_expr__30(stream, pos1, ref1, context) do
        {:ok, pos2, ref2, Parser.merge_captures(cap0, cap1)}
      else
        _fail -> :fail
      end
    end

    def parse_expr__34(stream, pos, ref_stack, context) do
      case parse_rule__class_atom(stream, pos, ref_stack, context) do
        {:ok, new_pos, new_ref_stack, sub_captures} ->
          {:ok, new_pos, new_ref_stack, from: {:rule, :class_atom, sub_captures}}

        _fail ->
          :fail
      end
    end

    def parse_expr__35(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :DASH) do
        {:ok, new_pos, text, nil} -> {:ok, new_pos, ref_stack, DASH: {:token, :DASH, text}}
        {:ok, new_pos, _text, capture} -> {:ok, new_pos, ref_stack, DASH: capture}
        :fail -> :fail
      end
    end

    def parse_expr__37(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :RBRACKET) do
        {:ok, new_pos, text, nil} ->
          {:ok, new_pos, ref_stack, RBRACKET: {:token, :RBRACKET, text}}

        {:ok, new_pos, _text, capture} ->
          {:ok, new_pos, ref_stack, RBRACKET: capture}

        :fail ->
          :fail
      end
    end

    def parse_expr__36(stream, pos, ref_stack, context) do
      Parser.not_pred(&parse_expr__37/4, stream, pos, ref_stack, context)
    end

    def parse_expr__38(stream, pos, ref_stack, context) do
      case parse_rule__class_atom(stream, pos, ref_stack, context) do
        {:ok, new_pos, new_ref_stack, sub_captures} ->
          {:ok, new_pos, new_ref_stack, to: {:rule, :class_atom, sub_captures}}

        _fail ->
          :fail
      end
    end

    def parse_rule__range(stream, pos, ref_stack, context) do
      with {:ok, pos1, ref1, cap0} <- parse_expr__34(stream, pos, ref_stack, context),
           {:ok, pos2, ref2, cap1} <- parse_expr__35(stream, pos1, ref1, context),
           {:ok, pos3, ref3, cap2} <- parse_expr__36(stream, pos2, ref2, context),
           {:ok, pos4, ref4, cap3} <- parse_expr__38(stream, pos3, ref3, context) do
        {:ok, pos4, ref4,
         Parser.merge_captures(
           cap0,
           Parser.merge_captures(cap1, Parser.merge_captures(cap2, cap3))
         )}
      else
        _fail -> :fail
      end
    end

    def parse_expr__39(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :LBRACKET) do
        {:ok, new_pos, text, nil} ->
          {:ok, new_pos, ref_stack, LBRACKET: {:token, :LBRACKET, text}}

        {:ok, new_pos, _text, capture} ->
          {:ok, new_pos, ref_stack, LBRACKET: capture}

        :fail ->
          :fail
      end
    end

    def parse_expr__41(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :CARET) do
        {:ok, new_pos, text, nil} -> {:ok, new_pos, ref_stack, CARET: {:token, :CARET, text}}
        {:ok, new_pos, _text, capture} -> {:ok, new_pos, ref_stack, CARET: capture}
        :fail -> :fail
      end
    end

    def parse_expr__40(stream, pos, ref_stack, context) do
      Parser.opt(&parse_expr__41/4, stream, pos, ref_stack, context)
    end

    def parse_expr__43(stream, pos, ref_stack, context) do
      case parse_rule__class_item(stream, pos, ref_stack, context) do
        {:ok, new_pos, new_ref_stack, sub_captures} ->
          {:ok, new_pos, new_ref_stack, class_item: {:rule, :class_item, sub_captures}}

        _fail ->
          :fail
      end
    end

    def parse_expr__42(stream, pos, ref_stack, context) do
      Parser.plus(&parse_expr__43/4, stream, pos, ref_stack, context)
    end

    def parse_expr__44(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :RBRACKET) do
        {:ok, new_pos, text, nil} ->
          {:ok, new_pos, ref_stack, RBRACKET: {:token, :RBRACKET, text}}

        {:ok, new_pos, _text, capture} ->
          {:ok, new_pos, ref_stack, RBRACKET: capture}

        :fail ->
          :fail
      end
    end

    def parse_rule__char_class(stream, pos, ref_stack, context) do
      with {:ok, pos1, ref1, cap0} <- parse_expr__39(stream, pos, ref_stack, context),
           {:ok, pos2, ref2, cap1} <- parse_expr__40(stream, pos1, ref1, context),
           {:ok, pos3, ref3, cap2} <- parse_expr__42(stream, pos2, ref2, context),
           {:ok, pos4, ref4, cap3} <- parse_expr__44(stream, pos3, ref3, context) do
        {:ok, pos4, ref4,
         Parser.merge_captures(
           cap0,
           Parser.merge_captures(cap1, Parser.merge_captures(cap2, cap3))
         )}
      else
        _fail -> :fail
      end
    end

    def parse_expr__45(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :STAR) do
        {:ok, new_pos, text, nil} -> {:ok, new_pos, ref_stack, STAR: {:token, :STAR, text}}
        {:ok, new_pos, _text, capture} -> {:ok, new_pos, ref_stack, STAR: capture}
        :fail -> :fail
      end
    end

    def parse_expr__46(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :PLUS) do
        {:ok, new_pos, text, nil} -> {:ok, new_pos, ref_stack, PLUS: {:token, :PLUS, text}}
        {:ok, new_pos, _text, capture} -> {:ok, new_pos, ref_stack, PLUS: capture}
        :fail -> :fail
      end
    end

    def parse_expr__47(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :QUESTION) do
        {:ok, new_pos, text, nil} ->
          {:ok, new_pos, ref_stack, QUESTION: {:token, :QUESTION, text}}

        {:ok, new_pos, _text, capture} ->
          {:ok, new_pos, ref_stack, QUESTION: capture}

        :fail ->
          :fail
      end
    end

    def parse_expr__48(stream, pos, ref_stack, context) do
      case parse_rule__bound(stream, pos, ref_stack, context) do
        {:ok, new_pos, new_ref_stack, sub_captures} ->
          {:ok, new_pos, new_ref_stack, bound: {:rule, :bound, sub_captures}}

        _fail ->
          :fail
      end
    end

    def parse_rule__quant(stream, pos, ref_stack, context) do
      Parser.try_alts(
        [&parse_expr__45/4, &parse_expr__46/4, &parse_expr__47/4, &parse_expr__48/4],
        stream,
        pos,
        ref_stack,
        context
      )
    end

    def parse_expr__49(stream, pos, ref_stack, context) do
      case parse_rule__atom(stream, pos, ref_stack, context) do
        {:ok, new_pos, new_ref_stack, sub_captures} ->
          {:ok, new_pos, new_ref_stack, atom: {:rule, :atom, sub_captures}}

        _fail ->
          :fail
      end
    end

    def parse_expr__51(stream, pos, ref_stack, context) do
      case parse_rule__quant(stream, pos, ref_stack, context) do
        {:ok, new_pos, new_ref_stack, sub_captures} ->
          {:ok, new_pos, new_ref_stack, quant: {:rule, :quant, sub_captures}}

        _fail ->
          :fail
      end
    end

    def parse_expr__50(stream, pos, ref_stack, context) do
      Parser.opt(&parse_expr__51/4, stream, pos, ref_stack, context)
    end

    def parse_rule__piece(stream, pos, ref_stack, context) do
      with {:ok, pos1, ref1, cap0} <- parse_expr__49(stream, pos, ref_stack, context),
           {:ok, pos2, ref2, cap1} <- parse_expr__50(stream, pos1, ref1, context) do
        {:ok, pos2, ref2, Parser.merge_captures(cap0, cap1)}
      else
        _fail -> :fail
      end
    end

    def parse_expr__52(stream, pos, ref_stack, context) do
      case parse_rule__range(stream, pos, ref_stack, context) do
        {:ok, new_pos, new_ref_stack, sub_captures} ->
          {:ok, new_pos, new_ref_stack, range: {:rule, :range, sub_captures}}

        _fail ->
          :fail
      end
    end

    def parse_expr__53(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :SHORTHAND_CLASS) do
        {:ok, new_pos, text, nil} ->
          {:ok, new_pos, ref_stack, SHORTHAND_CLASS: {:token, :SHORTHAND_CLASS, text}}

        {:ok, new_pos, _text, capture} ->
          {:ok, new_pos, ref_stack, SHORTHAND_CLASS: capture}

        :fail ->
          :fail
      end
    end

    def parse_expr__54(stream, pos, ref_stack, context) do
      case parse_rule__class_atom(stream, pos, ref_stack, context) do
        {:ok, new_pos, new_ref_stack, sub_captures} ->
          {:ok, new_pos, new_ref_stack, class_atom: {:rule, :class_atom, sub_captures}}

        _fail ->
          :fail
      end
    end

    def parse_rule__class_item(stream, pos, ref_stack, context) do
      Parser.try_alts(
        [&parse_expr__52/4, &parse_expr__53/4, &parse_expr__54/4],
        stream,
        pos,
        ref_stack,
        context
      )
    end

    def parse_expr__55(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :ESCAPED_CHAR) do
        {:ok, new_pos, text, nil} ->
          {:ok, new_pos, ref_stack, ESCAPED_CHAR: {:token, :ESCAPED_CHAR, text}}

        {:ok, new_pos, _text, capture} ->
          {:ok, new_pos, ref_stack, ESCAPED_CHAR: capture}

        :fail ->
          :fail
      end
    end

    def parse_expr__56(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :CARET) do
        {:ok, new_pos, text, nil} -> {:ok, new_pos, ref_stack, CARET: {:token, :CARET, text}}
        {:ok, new_pos, _text, capture} -> {:ok, new_pos, ref_stack, CARET: capture}
        :fail -> :fail
      end
    end

    def parse_expr__57(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :DASH) do
        {:ok, new_pos, text, nil} -> {:ok, new_pos, ref_stack, DASH: {:token, :DASH, text}}
        {:ok, new_pos, _text, capture} -> {:ok, new_pos, ref_stack, DASH: capture}
        :fail -> :fail
      end
    end

    def parse_expr__58(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :COMMA) do
        {:ok, new_pos, text, nil} -> {:ok, new_pos, ref_stack, COMMA: {:token, :COMMA, text}}
        {:ok, new_pos, _text, capture} -> {:ok, new_pos, ref_stack, COMMA: capture}
        :fail -> :fail
      end
    end

    def parse_expr__59(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :DIGIT) do
        {:ok, new_pos, text, nil} -> {:ok, new_pos, ref_stack, DIGIT: {:token, :DIGIT, text}}
        {:ok, new_pos, _text, capture} -> {:ok, new_pos, ref_stack, DIGIT: capture}
        :fail -> :fail
      end
    end

    def parse_expr__60(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :LITERAL_CHAR) do
        {:ok, new_pos, text, nil} ->
          {:ok, new_pos, ref_stack, LITERAL_CHAR: {:token, :LITERAL_CHAR, text}}

        {:ok, new_pos, _text, capture} ->
          {:ok, new_pos, ref_stack, LITERAL_CHAR: capture}

        :fail ->
          :fail
      end
    end

    def parse_rule__class_atom(stream, pos, ref_stack, context) do
      Parser.try_alts(
        [
          &parse_expr__55/4,
          &parse_expr__56/4,
          &parse_expr__57/4,
          &parse_expr__58/4,
          &parse_expr__59/4,
          &parse_expr__60/4
        ],
        stream,
        pos,
        ref_stack,
        context
      )
    end

    (
      @doc "Tokenizes `input` completely via maximal munch, applies any `@keywords`/`@refine` rules, or reports the first position nothing matches. `context` is read-only and only ever consulted by a `Grammar.IR.CustomLexeme` `@native(...)` token, if the grammar has one."
      @spec tokenize(String.t(), term()) :: {:ok, [Token.t()]} | {:error, Ichor.Error.t()}
      def tokenize(input, context \\ nil) do
        with {:ok, input} <- Grammar.Source.validate(input),
             {:ok, raw_tokens} <-
               Tokenizer.tokenize(fn inp -> lex_candidates(inp, context) end, input) do
          Grammar.Lexer.reclassify(raw_tokens, %{})
        end
      end
    )

    @doc "Matches `input` against the grammar's root rule, requiring the entire (tokenized) input to be consumed. A bare recognizer -- no `Ichor.Actions` involved. `context` is read-only and only ever consulted by a `Grammar.IR.Custom` `@native(...)` node, if the grammar has one."
    @spec parse(String.t(), term()) ::
            {:ok, non_neg_integer(), Ichor.Capture.raw_captures()} | {:error, Ichor.Error.t()}
    def parse(input, context \\ nil) do
      with {:ok, tokens} <- tokenize(input, context) do
        stream = List.to_tuple(tokens)

        case parse_rule__expr(stream, 0, [0], context) do
          {:ok, pos, _ref_stack, raw_captures} when pos == tuple_size(stream) ->
            {:ok, pos, raw_captures}

          {:ok, pos, _ref_stack, _raw_captures} ->
            {:error, Parser.unexpected_token_error(stream, pos, input)}

          _fail ->
            {:error,
             Ichor.Error.new(
               message: "input does not match #{inspect(:expr)}",
               stage: :parser,
               source: input
             )}
        end
      end
    end

    @doc "Like `parse/1`, but runs the match through the compile-time-known Actions module, returning the grammar's actual evaluated result."
    @spec run(String.t(), Ichor.Actions.context()) ::
            {:ok, term()} | {:error, Ichor.Error.t() | [Ichor.Error.t()]}
    def run(input, initial_context \\ nil) do
      with {:ok, _pos, raw_captures} <- parse(input, initial_context),
           {:ok, value, _context} <-
             Ichor.Actions.evaluate(:expr, raw_captures, Xeger.Parser.Actions, initial_context, %{
               atom: MapSet.new([]),
               bound: MapSet.new([:DIGIT]),
               group: MapSet.new([]),
               concat: MapSet.new([:piece]),
               expr: MapSet.new([:PIPE, :concat]),
               range: MapSet.new([]),
               char_class: MapSet.new([:class_item]),
               quant: MapSet.new([]),
               piece: MapSet.new([]),
               class_item: MapSet.new([]),
               class_atom: MapSet.new([])
             }) do
        {:ok, value}
      end
    end

    @doc "Like `run/2`, but evaluates `input` as a sequence of top-level matches against the root rule, one after another, threading context from each into the next (loading a standard-library file one top-level form at a time is the motivating case -- most grammars only ever need `run/2`)."
    @spec run_sequence(String.t(), Ichor.Actions.context()) ::
            {:ok, [term()], Ichor.Actions.context()}
            | {:error, Ichor.Error.t() | [Ichor.Error.t()]}
    def run_sequence(input, initial_context) do
      with {:ok, tokens} <- tokenize(input, initial_context) do
        do_run_sequence(List.to_tuple(tokens), 0, initial_context, [])
      end
    end

    def do_run_sequence(stream, pos, ctx, acc) do
      pos = Parser.skip_leading_trivia(stream, pos, nil)

      if pos >= tuple_size(stream) do
        {:ok, Enum.reverse(acc), ctx}
      else
        case parse_rule__expr(stream, pos, [0], ctx) do
          {:ok, new_pos, _ref_stack, raw_captures} ->
            case Ichor.Actions.evaluate(:expr, raw_captures, Xeger.Parser.Actions, ctx, %{
                   atom: MapSet.new([]),
                   bound: MapSet.new([:DIGIT]),
                   group: MapSet.new([]),
                   concat: MapSet.new([:piece]),
                   expr: MapSet.new([:PIPE, :concat]),
                   range: MapSet.new([]),
                   char_class: MapSet.new([:class_item]),
                   quant: MapSet.new([]),
                   piece: MapSet.new([]),
                   class_item: MapSet.new([]),
                   class_atom: MapSet.new([])
                 }) do
              {:ok, value, new_ctx} -> do_run_sequence(stream, new_pos, new_ctx, [value | acc])
              {:error, _} = err -> err
            end

          _fail ->
            {:error, Ichor.Error.new(message: "input does not match #{inspect(:expr)}", stage: :parser)}
        end
      end
    end
  )
end
